version: '3.9'
services:
  app:
    restart: always
    image: 127.0.0.1:5000/node_mongo
    build: .
    ports:
      - '80:3000'
    depends_on:
      - mongo
    deploy:
      replicas: 3
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8084:8080
