version: '3'
services:
  app:
    image: node 
    ports:
      - '80:3000'
    depends_on:
      - mongo
    deploy:
      replicas: 3

  mongo:
    image: mongo
    ports:
      - '27017:27017'
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:8080

